; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$TTL	300
secure.arthur-joppart.sb.uclllabs.be.   IN      CAA     0 issue "letsencrypt.org"
secure.arthur-joppart.sb.uclllabs.be.   IN      CAA     0 iodef "mailto:arthur.joppart@student.ucll.be"

@	IN	SOA	ns.arthur-joppart.sb.uclllabs.be. root.arthur-joppart.sb.uclllabs.be. (
			      	697145	; Serial
			 	300	; Refresh
			  	300	; Retry
				300	; Expire
			  	300 )	; Negative Cache TTL
;Name servers
arthur-joppart.sb.uclllabs.be.	IN	NS	ns.arthur-joppart.sb.uclllabs.be.
arthur-joppart.sb.uclllabs.be.	IN	NS	ns1.uclllabs.be.
arthur-joppart.sb.uclllabs.be.	IN	NS	ns2.uclllabs.be.
;records
ns	IN	AAAA	2001:6a8:2880:a077::85
arthur-joppart.sb.uclllabs.be.	IN	AAAA	2001:6a8:2880:a077::85
@	IN	MX	10 mx
mx	IN	A	193.191.177.133
mail	IN	A	193.191.177.133
ns	IN	A	193.191.177.133
@	IN	A	193.191.177.133
www	IN	A	193.191.177.133
www1	IN	A	193.191.177.133
www2	IN	A	193.191.177.133
secure	IN	A	193.191.177.133
supersecure	IN	A	193.191.177.133
test	IN	A	193.191.177.254
testerzone	IN	A	193.191.177.133
testerzone	IN	A	193.191.177.133
testerzone	IN	A	193.191.177.133
testerzone	IN	A	193.191.177.133
krakrak	IN	A	193.191.177.133
donk	IN	A	193.191.177.133
donkydonk	IN	A	193.191.177.133
testsub     IN      A       193.191.177.133
testsub     IN      A       193.191.177.133
nognentest	IN	A	193.191.177.133
enkeletesten	IN	A	193.191.177.133
mail2     IN      A       193.191.177.133
mail3     IN      A       193.191.177.133
mail4     IN      A       193.191.177.133
wwwtest     IN      CNAME       www
wwwtest1     IN      CNAME       www1
wwwfoemp     IN      CNAME       www
epischevhost	IN	A	193.191.177.133
kronker	IN	A	193.191.177.133
kronker2	IN	A	193.191.177.133
subzonepe8soh	IN	A	193.191.177.133
subzoneeng5iw	IN	A	193.191.177.133
subzonepook2o	IN	A	193.191.177.133
subzoneeegum4	IN	A	193.191.177.133
t	IN	A	193.191.177.133
subzoneuo3hoh	IN	A	193.191.177.133
subzoneeec9oo	IN	A	193.191.177.133
subzonexoom4p	IN	A	193.191.177.133
subzonezo2wae	IN	A	193.191.177.133
subzonenei4oh	IN	A	193.191.177.133
subzonenaida1	IN	A	193.191.177.133
subzoneawai1i	IN	A	193.191.177.133
subzonesahy5x	IN	A	193.191.177.133
subzoneoong8i	IN	A	193.191.177.133
subzonegimoo7	IN	A	193.191.177.133
subzoneeov8ee	IN	A	193.191.177.133
subzoneeezoo2	IN	A	193.191.177.133
subzonewi7hoh	IN	A	193.191.177.133
subzonegaht1a	IN	A	193.191.177.133
subzonethe2ei	IN	A	193.191.177.133
subzoneay2bah	IN	A	193.191.177.133
subzoneao4ro3	IN	A	193.191.177.133
subzoneeengo3	IN	A	193.191.177.133
subzonephaz1u	IN	A	193.191.177.133
subzonetesai6	IN	A	193.191.177.133
subzoneoeshi8	IN	A	193.191.177.133
subzoneol3oom	IN	A	193.191.177.133
subzonememie1	IN	A	193.191.177.133
subzonepaelo5	IN	A	193.191.177.133
subzonesa5aej	IN	A	193.191.177.133
subzoneahb5ah	IN	A	193.191.177.133
subzonete9iif	IN	A	193.191.177.133
subzonena3ieg	IN	A	193.191.177.133
subzonepu4bai	IN	A	193.191.177.133
subzonethee3a	IN	A	193.191.177.133
subzoneuo5luc	IN	A	193.191.177.133
subzonelai8au	IN	A	193.191.177.133
subzoneohh1ju	IN	A	193.191.177.133
subzoneouvee1	IN	A	193.191.177.133
subzonesi4xu7	IN	A	193.191.177.133
subzonezai8ul	IN	A	193.191.177.133
subzoneaik7da	IN	A	193.191.177.133
subzonehoo8ei	IN	A	193.191.177.133
subzoneeiz4ve	IN	A	193.191.177.133
subzoneaiy7ai	IN	A	193.191.177.133
subzonevihih6	IN	A	193.191.177.133
t	IN	A	193.191.177.133
klakklak     IN      A       193.191.177.133
klakklak	IN	A	193.191.177.133
klakklak     IN      A       193.191.177.133
styn	IN	A	193.191.177.133
styn.arthur-joppart.sb.uclllabs.be	IN	A	193.191.177.133
oobi3g.subzonezo2wae	IN	A	193.191.177.133
klonky	IN	A	193.191.177.133
klonk.klonky	IN	A	193.191.177.133
aaa	IN	A	193.191.177.133
bbb	IN	A	193.191.177.133
subzoneaet9es	IN	A	193.191.177.133
ccc	IN	A	193.191.177.133
ddd	IN	A	193.191.177.133
eee	IN	A	193.191.177.133
subzoneahc4up	IN	A	193.191.177.133
subzoneohb7oo	IN	A	193.191.177.133
subzonedo9koh	IN	A	193.191.177.133
subzonekoo9hu	IN	A	193.191.177.133
subzoneat7the	IN	A	193.191.177.133
subzonehe2iec	IN	A	193.191.177.133
subzonedeep5p	IN	A	193.191.177.133
subzoneiek3er	IN	A	193.191.177.133
subzoneeo4mie	IN	A	193.191.177.133
subzoneeil9oo	IN	A	193.191.177.133
subzoneuv9air	IN	A	193.191.177.133
subzoneiev4ki	IN	A	193.191.177.133
subzoneaipi5i	IN	A	193.191.177.133
subzonenah6ai	IN	A	193.191.177.133
subzoneoj7ieg	IN	A	193.191.177.133
subzonedi1gir	IN	A	193.191.177.133
subzoneda9nom	IN	A	193.191.177.133
subzoneaup6so	IN	A	193.191.177.133
subzonejie3co	IN	A	193.191.177.133
subzonekaegh9	IN	A	193.191.177.133
subzonehohx0y	IN	A	193.191.177.133
subzonetee3lo	IN	A	193.191.177.133
subzonemahn4p	IN	A	193.191.177.133
subzonetah2fe	IN	A	193.191.177.133
subzoneeib2eo	IN	A	193.191.177.133
subzonewiew5v	IN	A	193.191.177.133
subzoneul6eku	IN	A	193.191.177.133
subzonesu2aib	IN	A	193.191.177.133
subzonechah7k	IN	A	193.191.177.133
subzoneeiroh8	IN	A	193.191.177.133
subzoneeezai5	IN	A	193.191.177.133
subzonegimie9	IN	A	193.191.177.133
subzoneaex4za	IN	A	193.191.177.133
subzonema8ohh	IN	A	193.191.177.133
subzoneloich7	IN	A	193.191.177.133
subzoneshoo6a	IN	A	193.191.177.133
subzoneatoh9e	IN	A	193.191.177.133
subzoneaa2ina	IN	A	193.191.177.133
subzoneiek2ee	IN	A	193.191.177.133
subzonehoob9t	IN	A	193.191.177.133
subzonetei1oc	IN	A	193.191.177.133
subzonepaej4s	IN	A	193.191.177.133
subzoneleig9u	IN	A	193.191.177.133
subzonephi9wo	IN	A	193.191.177.133
subzonephah9s	IN	A	193.191.177.133
subzoneahn1gu	IN	A	193.191.177.133
subzonebe3jae	IN	A	193.191.177.133
subzoneux6oer	IN	A	193.191.177.133
subzoneeihie5	IN	A	193.191.177.133
subzoneruth6a	IN	A	193.191.177.133
subzoneequee9	IN	A	193.191.177.133
subzoneeifee0	IN	A	193.191.177.133
subzoneahj0me	IN	A	193.191.177.133
subzonekuez6e	IN	A	193.191.177.133
subzonejueph7	IN	A	193.191.177.133
subzonefo7aiv	IN	A	193.191.177.133
subzoneohch0g	IN	A	193.191.177.133
subzonecaej1i	IN	A	193.191.177.133
subzonever0ah	IN	A	193.191.177.133
subzoneahf5oo	IN	A	193.191.177.133
subzoneacai1e	IN	A	193.191.177.133
subzoneniu7vi	IN	A	193.191.177.133
subzoneais2og	IN	A	193.191.177.133
subzonequo5au	IN	A	193.191.177.133
subzonepa6noo	IN	A	193.191.177.133
subzoneyoo9oj	IN	A	193.191.177.133
subzoneaew7mi	IN	A	193.191.177.133
subzoneaa2aph	IN	A	193.191.177.133
subzonewah3je	IN	A	193.191.177.133
ttt	IN	NS	ns.arthur-joppart.sb.uclllabs.be.
subzoneaesa3s	IN	NS	ns.arthur-joppart.sb.uclllabs.be.
aeb6ew.subzoneaesa3s	IN	A	193.191.177.133
